### ISSUE TITLE
Key specifications

### ISSUE THREAD

**Issue by ssavvides** [cisco/jfnr#1]
enc/dec fails if key does not adhere to specifications (128, 192, 256 bits; expressed as a byte string), e.g for (dummy) key byte[] key = "key".getBytes();

Add an assertion?

**Comment by sashank** [comment]
Thanks , feel free to add it and give a pull request ? would be happy to merge it.

**Comment by sashank** [comment]
added the assertions , for now only 128 bit keys are supported. hope it helps ! thanks again for bringing this up.
